# Generated by Django 3.0.7 on 2020-06-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20200619_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
