# Generated by Django 3.0.7 on 2020-06-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_auto_20200620_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet',
            new_name='text',
        ),
    ]
