# Generated by Django 3.0.7 on 2020-06-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_auto_20200620_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
    ]
